# Al Jabar Matriks

Matriks adalah susunan berupa bilangan-bilangan atau elemen-elemen yang disusun dalam baris dan kolom. Matriks direpresentasikan dalam bentuk tabel dengan baris-baris dan kolom-kolom. Setiap elemen dalam matriks diberi indeks berdasarkan posisinya dalam baris dan kolom.

# Jenis-jenis matiks dan Contohnya

1. Matriks Nol

   Matriks di mana semua elemennya adalah nol.
   
   Contoh:

   $
   \begin{bmatrix}
   0 & 0 \\
   0 & 0 \\
   \end{bmatrix}
   $

2. Matriks Identitas

   Adalah matriks persegi di mana semua elemen di diagonal utamanya adalah 1 dan elemen-elemen lainnya adalah 0.

   Contoh:

   $
   \begin{bmatrix} 
   1 & 0 \\ 
   0 & 1 \\
   \end{bmatrix}
   $

3. Matriks Diagonal

   Adalah matriks di mana semua elemen di luar diagonal utama adalah nol.

   Contoh:

   $
   \begin{bmatrix} 
   2 & 0 & 0 \\ 
   0 & 3 & 0 \\ 
   0 & 0 & 4 \\
   \end{bmatrix}
   $

4. Matriks Segitiga Atas

   Adalah matriks di mana semua elemen di bawah diagonal utama adalah nol.

   Contoh:

   $
   \begin{bmatrix}
   1 & 2 & 3 \\ 
   0 & 4 & 5 \\ 
   0 & 0 & 6 \\
   \end{bmatrix}
   $

5. Matriks Segitiga Bawah

   Adalah matriks di mana semua elemen di atas diagonal utama adalah nol.

   Contoh:

   $
   \begin{bmatrix} 
   1 & 0 & 0 \\ 
   2 & 3 & 0 \\ 
   4 & 5 & 6 \\
   \end{bmatrix}
   $

6. Matriks Simetris

   Adalah matriks di mana elemen-elemennya simetris terhadap diagonal utama.

   Contoh:

   $
   \begin{bmatrix} 
   1 & 2 & 3 \\ 
   2 & 4 & 5 \\ 
   3 & 5 & 6 \\
   \end{bmatrix}
   $

7. Matriks Ortogonal

   Adalah matriks persegi di mana perkaliannya dengan transposenya menghasilkan matriks identitas.

   Contoh:

   $
   \begin{bmatrix} 
   0 & 1 \\ 
   1 & 0 \\
   \end{bmatrix}
   $

8. Matriks Singular

   Adalah matriks di mana determinannya sama dengan nol.

   Contoh:

   $
   \begin{bmatrix} 
   1 & 2 \\ 
   2 & 4 \\
   \end{bmatrix}
   $

# Operasi Sistem Persamaan Linear

## 1. Penjumlahan dan Pengurangan
Persamaan-persamaan dalam sistem dapat ditambah atau dikurangi satu sama lain untuk menghilangkan variabel tertentu. Misal:

$$ a1x + b1y = c1 \\
a2x + b2y = c2 \\ $$

Kita bisa mengurangkan persamaan kedua dari persamaan pertama untuk menghilangkan variabel $x$ dan $y$.


In [1]:
# Contoh implementasi dengan numpy
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[6,5,4],[3,2,1]])

print(A+B)
print(A-B)

[[7 7 7]
 [7 7 7]]
[[-5 -3 -1]
 [ 1  3  5]]


## 2. Perkalian
Perkalian matriks adalah proses dengan mengalikan elemen-elemen baris dari matriks pertama dengan elemen-elemen kolom dari matriks kedua dan menjumlahkan hasil perkalian tersebut.

In [2]:
# Contoh implementasi dengan numpy
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[6,5],[4,3],[2,1]])

print(A@B)

[[20 14]
 [56 41]]


## 3. Transpose
Transpose matriks adalah operasi yang mengubah baris menjadi kolom dan sebaliknya. Dalam transpose, elemen-elemen diagonal utama tetap tidak berubah, tetapi elemen-elemen di luar diagonal utama dipindahkan ke posisi yang sesuai. Misalnya, jika A adalah matriks dengan ukuran m x n, maka transpose dari A ditulis sebagai $A^T$ yang akan menjadi matriks dengan ukuran n x m, dimana elemen-elemen baris pada A menjadi $A^T$.

In [4]:
# Contoh implementasi dengan numpy
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
C = np.transpose(A)

print(A)
print(C)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## Berikut adalah contoh kode Python yang mengalikan dua matrix menggunakan perulangan

In [3]:
def mul_matrix(a, b):
  if len(a[0]) != len(b):
    print("error --- require", len(a[0]), "but found", len(b), "error matrix")
    return None

  result = []
  for i in range(len(a)):
    row = []
    for j in range(len(b[0])):
      total = 0
      for k in range(len(b)):
        total += a[i][k] * b[k][j]
      row.append(total)
    result.append(row)

  return result

# Contoh Penggunaan
matrix1 = [[1, 3, 3], [4, 6, 6]]
matrix2 = [[7, 9], [9, 10], [11, 12]]

result = mul_matrix(matrix1, matrix2)
if result:
    print("Hasil perkalian matriks:")
    for row in result:
        print(row)

Hasil perkalian matriks:
[67, 75]
[148, 168]
