# Algoritma KAL

# Algoritma PageRank

## Deskripsi Algoritma PageRank
Algoritma PageRank adalah sebuah algoritma yang digunakan oleh mesin pencari Google untuk menentukan peringkat halaman web dalam hasil pencarian. Algoritma ini didasarkan bahwa halaman web yang penting kemungkinan besar akan menerima lebih banyak tautan dari halaman web lainnya.

## Konsep Algoritma PageRank
PageRank memiliki konsep dasar dimana dalam setiap halaman akan diperhitungkan inbound link(link masuk) dan outbound link(link keluar) dari setiap halaman web. Tetapi tidak hanya itu, dengan melakukan pendekatan yang prosesnya terjadi secara rekursif dimana sebuah rangking akan ditentukan oleh rangking dari halaman web rangking yang rankingnya ditentukan oleh ranking halaman web lain yang memiliki link ke halaman tersebut. Proses ini berarti suatu proses yang berulang(rekursif).

## Contoh Pengerjaan PageRank
$$r_j = \sum\limits_{i=1}\frac{r_i}{d_i}$$

$r_0 = \frac{r_4}{3}$

$r_1 = \frac{r_2}{2}+\frac{r_4}{3}+r_3$

$r_2 = \frac{r_0}{3}+\frac{r_4}{3}$

$r_3 = \frac{r_2}{2}+\frac{r_0}{3}$

$r_4 = \frac{r_0}{3}+r_1$

$A = \begin{bmatrix}
0 & 0 & 0 & 0 & \frac{1}{3}\\
0 & 0 & \frac{1}{2} & 1 & \frac{1}{3}\\
\frac{1}{3} & 0 & 0 & 0 & \frac{1}{3}\\
\frac{1}{3} & 0 & \frac{1}{2} & 0 & 0\\
\frac{1}{3} & 1 & 0 & 0 & 0\\
\end{bmatrix}$

$V0 = \begin{bmatrix}
0,2 \\ 0,2 \\ 0,2 \\ 0,2 \\ 0,2\\
\end{bmatrix}$

toleransi = 0,01

In [1]:
import numpy as np

A = np.array([[0,0,0,0,1/3],[0,0,1/2,1,1/3],[1/3,0,0,0,1/3],[1/3,0,1/2,0,0],[1/3,1,0,0,0]])
v0 = np.array([[0.2],[0.2],[0.2],[0.2],[0.2]])

v1 = A @ v0
print(v1)

[[0.06666667]
 [0.36666667]
 [0.13333333]
 [0.16666667]
 [0.26666667]]


In [2]:
v2 = A @ v1
print(v2)

[[0.08888889]
 [0.32222222]
 [0.11111111]
 [0.08888889]
 [0.38888889]]


In [4]:
v3 = A @ v2
print(v3)

[[0.12962963]
 [0.27407407]
 [0.15925926]
 [0.08518519]
 [0.35185185]]


In [5]:
v4 = A @ v3
print(v4)

[[0.11728395]
 [0.28209877]
 [0.16049383]
 [0.12283951]
 [0.31728395]]


In [6]:
v5 = A @ v4
print(v5)

[[0.10576132]
 [0.30884774]
 [0.14485597]
 [0.11934156]
 [0.32119342]]


$$\begin{vmatrix}V_{i+1}-V_i\end{vmatrix}^2$$

$= \begin{pmatrix}0,10-0,11\end{pmatrix}^2 + \begin{pmatrix}0,30-0,28\end{pmatrix}^2 + \begin{pmatrix}0,14-0,16\end{pmatrix}^2 + \begin{pmatrix}0,11-0,12\end{pmatrix}^2 + \begin{pmatrix}0,32-0,31\end{pmatrix}^2$

$= \begin{pmatrix}0,01\end{pmatrix}^2 + \begin{pmatrix}0,02\end{pmatrix}^2 + \begin{pmatrix}0,02\end{pmatrix}^2 +
\begin{pmatrix}0,01\end{pmatrix}^2 + \begin{pmatrix}0,01\end{pmatrix}^2$

$= 0,0001 + 0,0004 + 0,0004 + 0,0001 + 0,0001$

$= 0,0011 < 0,01$

In [10]:
a = (0.10 - 0.11)**2
b = (0.30 - 0.28)**2
c = (0.14 - 0.16)**2
d = (0.11 - 0.12)**2
e = (0.32 - 0.31)**2

f = a + b + c + d + e

print(f)

0.0010999999999999981


In [1]:
import numpy as np

def kondisi(v0, v1):
    a = 0
    for i in range(len(v0)):
        a += (v1[i] - v0[i]) ** 2
    return a[0]

def kali(mat, v0, v1):
    a = kondisi(v0, v1)
    loop = 2
    print(a, "< 0.01")
    loop = 0
    while a > 0.01:
        loop += 1
        new = np.dot(mat, v1)
        a = kondisi(v1, new)
        print(f"v{loop}")
        print(new)
        print()
        print(a, "< 0.01")
        print()
        v1 = new

A = np.array([[0,0,0,0,1/3],[0,0,1/2,1,1/3],[1/3,0,0,0,1/3],[1/3,0,1/2,0,0],[1/3,1,0,0,0]])
print("A =",A)
print()
v0 = np.array([[1/5],[1/5],[1/5],[1/5],[1/5]])
print("v0 =",v0)
print()
v1 = A @ v0
print("v1 =",v1)
print()

kali(A, v0, v1)

A = [[0.         0.         0.         0.         0.33333333]
 [0.         0.         0.5        1.         0.33333333]
 [0.33333333 0.         0.         0.         0.33333333]
 [0.33333333 0.         0.5        0.         0.        ]
 [0.33333333 1.         0.         0.         0.        ]]

v0 = [[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]

v1 = [[0.06666667]
 [0.36666667]
 [0.13333333]
 [0.16666667]
 [0.26666667]]

0.05555555555555557 < 0.01
v1
[[0.08888889]
 [0.32222222]
 [0.11111111]
 [0.08888889]
 [0.38888889]]

0.023950617283950627 < 0.01

v2
[[0.12962963]
 [0.27407407]
 [0.15925926]
 [0.08518519]
 [0.35185185]]

0.007681755829903978 < 0.01

