# Determinan

Determinan adalah ukuran skalar dari matriks. Determinan hanya berlaku untuk matriks bujur sangkar.

# Sifat-sifat Determinan
## 1. Determinan dari matriks identitas adalah 1.

In [2]:
import numpy as np
A = np.array([[2,3],[2,1]])
B = np.array([[2,4,3],[2,5,6],[2,5,1]])
C = np.array([[1,0],[0,1]])
D = np.array([[1,0,0],[0,1,0],[0,0,1]])

print(A,'\n')
print(B,'\n')
print(C,'\n')
print(D,'\n')

[[2 3]
 [2 1]] 

[[2 4 3]
 [2 5 6]
 [2 5 1]] 

[[1 0]
 [0 1]] 

[[1 0 0]
 [0 1 0]
 [0 0 1]] 



In [ ]:
A_det = np.linalg.det(C)
B_det = np.linalg.det(D)

print(A_det)
print(B_det)

1.0
1.0


In [ ]:
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)

print(A_inv)
print(B_inv)

[[-0.25  0.75]
 [ 0.5  -0.5 ]]
[[ 2.5 -1.1 -0.9]
 [-1.   0.4  0.6]
 [-0.   0.2 -0.2]]


## 2. Determinan matriks AB sama dengan determinan matriks A dikali determinan matriks B.

$det(AB) = det(A).det(B)$

Jika,

$I = A.A^{-1}$

maka,

$det(I) = det(A).det(A^{-1})$

sehingga,

$det(A^{-1}) = \frac{1}{det(A)}$

In [ ]:
# det(AB) = det(A.B)
det_AB = np.dot(A_det,B_det)

print(det_AB)

1.0


In [ ]:
# det(I) = det(A).det(A-1)
I = np.dot(A_det,A_inv)

print(I)

[[-0.25  0.75]
 [ 0.5  -0.5 ]]


## 3. Menukar baris atau kolom dari matriks akan mengubah tanda dari determinan.

In [ ]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])
print(A)

[[1 4 2]
 [1 1 1]
 [3 2 1]]


In [ ]:
A_det = np.linalg.det(A)

print(round(A_det))

5


In [ ]:
# menukar 1 baris/kolom matriks akan merubah tanda determinan
A1 = np.array([[1,1,1],[1,4,2],[3,2,1]])
A1_det = np.linalg.det(A1)

print(A1, '\n')
print(round(A1_det))

[[1 4 2]
 [1 1 1]
 [3 2 1]] 

-5


In [ ]:
A2 = np.array([[4,1,2],[1,1,1],[2,3,1]])
A2_det = np.linalg.det(A2)

print(A2, '\n')
print(round(A2_det))

[[4 1 2]
 [1 1 1]
 [2 3 1]] 

-5


## 4. Jika baris atau kolom dari matriks merupakan kelipatan dari baris atau kolom yang lain maka hasil determinannya akan sama dengan 0.

In [ ]:
A = np.array([[1,4,2],[2,8,4],[3,2,1]])
A_det = np.linalg.det(A)

print(A, '\n')
print(round(A_det))

[[1 4 2]
 [2 8 4]
 [3 2 1]] 

0


In [ ]:
B = np.array([[1,4,2],[2,8,3],[1,4,1]])
B_det = np.linalg.det(B)

print(B, '\n')
print(round(B_det))

[[1 4 2]
 [2 8 3]
 [1 4 1]] 

0


## 5. Jika determinan skalar K dan determinan matriks $A_{nXn}$ dikalikan, maka $det(K.A) = K^n.det(A)$.

In [3]:
K = 2
A = np.array([[1,4,2],[1,1,1],[3,2,1]])
A_det = np.linalg.det(A)
K_A = np.dot(K,A)

print(A, '\n')
print(round(A_det), '\n')
print(K_A)

[[1 4 2]
 [1 1 1]
 [3 2 1]] 

5 

[[2 8 4]
 [2 2 2]
 [6 4 2]]


In [ ]:
KA_det = np.linalg.det(K_A)

print(round(KA_det))

40


In [4]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])
B = np.array([[2,8,4],[1,1,1],[3,2,1]])

A_det = np.linalg.det(A)
B_det = np.linalg.det(B)

print(round(A_det))
print(round(B_det))

5
10


## 6. Melakukan operasi baris elementer terhadap matriks tidak akan merubah invers atau nilai.

In [ ]:
B = np.array([[1,4,2],[0,-3,-1],[3,2,1]])
B_det = np.linalg.det(B)

print(B,'\n')
print(round(B_det))

[[ 1  4  2]
 [ 0 -3 -1]
 [ 3  2  1]] 

5


## 7. Determinan A transpose sama dengan determinan A.

In [ ]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])
A_det = np.linalg.det(A)
A1 = np.transpose(A)
A1_det = np.linalg.det(A1)

print(A,'\n')
print(round(A_det), '\n')
print(A1, '\n')
print(round(A1_det))

[[1 4 2]
 [1 1 1]
 [3 2 1]] 

5 

[[1 1 3]
 [4 1 2]
 [2 1 1]] 

5


# Matriks Segitiga Atas

Adalah matriks bujur yang di bawah diagonal utama adalah nol.

Hasil determinannya merupakan hasil perkalian dari setiap diagonal.

In [ ]:
A = np.array([[2,3,1,2],[0,1,2,1],[0,0,5,2],[0,0,0,3]])
A_det = np.linalg.det(A)

print(A,'\n')
print(round(A_det))

[[2 3 1 2]
 [0 1 2 1]
 [0 0 5 2]
 [0 0 0 3]] 

30


In [5]:
A = np.array([[1,4,2],[0,4,1],[0,0,1]])
A_det = np.linalg.det(A)

print(A,'\n')
print(round(A_det))

[[1 4 2]
 [0 4 1]
 [0 0 1]] 

4


In [6]:
A = np.array([[4,2],[0,1]])
A_det = np.linalg.det(A)

print(A,'\n')
print(round(A_det))

[[4 2]
 [0 1]] 

4


# Ekspansi Kofaktor
Ekspansi kofaktor adalah cara untuk menemukan determinan matriks dengan mengalikan setiap elemen dalam baris atau kolom tertentu dengan kofaktornya, kemudian menjumlahkan hasilnya.

## Menghitung determinan matriks 4x4 menggunakan ekspansi kofaktor

$A = \begin{bmatrix}
3 & 1 & 0 & 2 \\
-1 & 2 & 4 & 1 \\
2 & 0 & 3 & -2 \\
1 & -3 & 2 & 1 \\
\end{bmatrix} = a_{11}c_{11} + a_{12}c_{12} + a_{13}c_{13} + a_{14}c_{14}$

$(-1)^{1+1}det = \begin{bmatrix}
2 & 4 & 1 \\
0 & 3 & -2 \\
-3 & 2 & 1 \\
\end{bmatrix}$

$(-1)^{1+2}det = \begin{bmatrix}
-1 & 4 & 1 \\
2 & 3 & -2 \\
1 & 2 & 1 \\
\end{bmatrix}$

$(-1)^{1+3}det = \begin{bmatrix}
-1 & 2 & 1 \\
2 & 0 & -2 \\
1 & -3 & 1 \\
\end{bmatrix}$

$(-1)^{1+4}det = \begin{bmatrix}
-1 & 2 & 4 \\
2 & 0 & 3 \\
1 & -3 & 2 \\
\end{bmatrix}$

$C_{11} = \begin{bmatrix}
2 & 4 & 1 \\
0 & 3 & -2 \\
-3 & 2 & 1 \\
\end{bmatrix}$

$2.(-1)^{1+1} det = \begin{bmatrix}
3 & -2 \\
2 & 1 \\
\end{bmatrix}$

$4.(-1)^{1+2} det = \begin{bmatrix}
0 & -2 \\
-3 & 1 \\
\end{bmatrix}$

$1.(-1)^{1+3} det = \begin{bmatrix}
0 & 3 \\
-3 & 2 \\
\end{bmatrix}$

$C_{11} = 2(3+4)-4(0-6)+1(0+9) = 47$

$C_{12} = \begin{bmatrix}
-1 & 4 & 1 \\
2 & 3 & -2 \\
1 & 2 & 1 \\
\end{bmatrix}$

$-1.(-1)^{1+1} det = \begin{bmatrix}
3 & -2 \\
2 & 1 \\
\end{bmatrix}$

$4.(-1)^{1+2} det = \begin{bmatrix}
2 & -2 \\
1 & 1 \\
\end{bmatrix}$

$1.(-1)^{1+3} det = \begin{bmatrix}
2 & 3 \\
1 & 2 \\
\end{bmatrix}$

$C_{12} = -1(3+4)-4(2+2)+1(4-3) = -22$

$C_{13} = \begin{bmatrix}
-1 & 2 & 1 \\
2 & 0 & -2 \\
1 & -3 & 1 \\
\end{bmatrix}$

$-1.(-1)^{1+1} det = \begin{bmatrix}
0 & -2 \\
-3 & 1 \\
\end{bmatrix}$

$2.(-1)^{1+2} det = \begin{bmatrix}
2 & -2 \\
1 & 1 \\
\end{bmatrix}$

$1.(-1)^{1+3} det = \begin{bmatrix}
2 & 0 \\
1 & -3 \\
\end{bmatrix}$

$C_{13} = -1(0-6)-2(2+2)+1(-6-0) = -8$

$C_{14} = \begin{bmatrix}
-1 & 2 & 4 \\
2 & 0 & 3 \\
1 & -3 & 2 \\
\end{bmatrix}$

$-1.(-1)^{1+1} det = \begin{bmatrix}
0 & 3 \\
-3 & 2 \\
\end{bmatrix}$

$2.(-1)^{1+2} det = \begin{bmatrix}
2 & 3 \\
1 & 2 \\
\end{bmatrix}$

$4.(-1)^{1+3} det = \begin{bmatrix}
2 & 0 \\
1 & -3 \\
\end{bmatrix}$

$C_{14} = -1(0+9)-2(4-3)+4(-6-0) = -35$

$A = \begin{bmatrix}
3 & 1 & 0 & 2 \\
-1 & 2 & 4 & 1 \\
2 & 0 & 3 & -2 \\
1 & -3 & 2 & 1 \\
\end{bmatrix} = a_{11}c_{11} + a_{12}c_{12} + a_{13}c_{13} + a_{14}c_{14}$

$= 3.(47)-1.(-22)+0(-8)-2(-35)$

$= 141 + 22 - 0 + 70$

$= 233$

In [3]:
import numpy as np
A = np.array([[3,1,0,2],[-1,2,4,1],[2,0,3,-2],[1,-3,2,1]])
A_det = np.linalg.det(A)

print(A)
print(round(A_det))

[[ 3  1  0  2]
 [-1  2  4  1]
 [ 2  0  3 -2]
 [ 1 -3  2  1]]
233
