# Konsep Eigenvalue dan Eigenvector
Terdapat matrik bujur sangkar A dengan derajat n. Jika terdapat vektor tidak nol dan skalar $\lambda$ sehingga

$$Ax = \lambda x$$

maka $\lambda$ disebut eigenvalue dari A, dan x disebut eigenvector yang nilainya bersesuai dengan eigenvalue $\lambda$.

Untuk menemukan eigenvalue, kita harus menyelesaikan:

$$det(A-\lambda)=0$$

Setelah mendapatkan $\lambda$, substitusikan kembali ke persamaan $(A-\lambda)x = 0$ untuk menemukan vector x.

# Contoh Menghitung Eigenvalue dan Eigenvactor Menggunakan Numpy
Matriks 2x2

In [ ]:
import numpy as np
from numpy.linalg import eig

# Matriks 2x2
A = np.array([[1,4],[2,3]])

# Menghitung eigenvalue dan eigenvector
w,v = eig(A)

print(A, '\n')
print('E-value', w, '\n')
print('E-value', v.round(), '\n')

Matriks ukuran 2x2
[[1 4]
 [2 3]] 

E-value [-1.  5.] 

E-value [[-1. -1.]
 [ 0. -1.]] 



Matriks 3x3

In [ ]:
import numpy as np
from numpy.linalg import eig

# Matriks 3x3
A = np.array([[1,4,1],[2,3,2],[2,4,5]])

# Menghitung eigenvalue dan eigenvector
w,v = eig(A)

print(A, '\n')
print('E-value', w.round(), '\n')
print('E-value', v.round(), '\n')

[[1 4 1]
 [2 3 2]
 [2 4 5]] 

E-value [ 8. -1.  2.] 

E-value [[-0. -1. -1.]
 [-0.  0. -0.]
 [-1.  0.  1.]] 



# Contoh Implementasi Eigenvalue dan Eigenvector
Implementasi PCA melalui EVD dengan python:

In [1]:
import numpy as np

def pcaSVD(X):
    n, p = X.shape
    X_centered = X - X.mean(axis=0)  # Pusatkan data

    u, sigma, vt = np.linalg.svd(X_centered, full_matrices=False)

    # Mengembalikan komponen utama dan eigenvalue
    return (X_centered @ vt.T), (sigma**2) / (n-1)

# Contoh Data
x = np.array([[1, 4], [2, 3]])

komponen_utama, eigenvalue = pcaSVD(x)
print("Komponen utama:\n", komponen_utama.round())
print("Eigenvalue:\n", eigenvalue.round())


Komponen utama:
 [[-1.  0.]
 [ 1. -0.]]
Eigenvalue:
 [1. 0.]


  * Terdapat fungsi pcaEVD dengan parameter x.
  * n, p = X.shape untuk mendapatkan jumlah sampel dan jumlah fitur dari bentuk matriks x.
  * x _= x.mean(axis=0) untuk mengurangkan mean dari setiap kolom data sehingga data memiliki mean 0.
  * u, sigma, vt = np.linalg.svd(X, full_matrices=False) untuk memecah matriks x menjadi tiga matriks u, sigma dan vt. 
  Matriks u adalah matriks ortogonal yang kolom-kolomya adalah vektor singular kiri. 
  Matriks sigma adalah vektor yang berisi singular values.
  Matriks vt adalah ortogonal yang baris-barisnya adalah vektor singular kanan.
  * return (X @ vt.T), (sigma^2) / (n-1) untuk mengembalikan nilai ke dalam fungsi.
  (X @ vt.T) adalah matriks hasil transformasi data asli ke ruang komponen utama.
  (sigma^2) / (n-1) adalah nilai eigen yang digunakan untuk menghitung proporsi variansi.