# Matriks Invers

Matriks Invers adalah matriks yang ketika dikalikan dengan matriks aslinya menghasilkan matriks identitas. Jika $A$ adalah suatu matriks dan $A^2$ adalah matriks invers, jadi

$A$ x $A^{-1}$ = $A^{-1}$ x $A$ = $I$

$I$ adalah matrik identitas yang memilki 1 di diagonal utama dan 0 di tempat lainnya. Matriks invers hanya ada untuk matriks persegi (matriks dengan jumlah baris sama dengan jumlah kolom).

# Sifat-sifat Matriks Invers

* Jika B dan C keduanya adalah invers dari A, maka B = C
* Hasil kali dari berapapun banyak matriks yang dapat dibalik adalah matriks yang dapat dibalik, sehingga invers dari hasil perkalian tersebut adalah hasil kali invers-inversnya dalam bentuk terbalik.
Contoh :

  $P$ = $A$ x $B$ x $C$ x ... x $Z$

  dan semua matriks A, B, C, ..., Z dapat dibalik, maka

  $P^{-1}$ = $A^{-1}$ x $B^{-1}$ x $C^{-1}$ x ... x $Z^{-1}$
* Jika A dan B matriks berukuran sama serta bisa dibalik, maka: AB dapat dibalik.

# Mencari Matriks Invers dengan Eliminasi Gauss Jordan

1. Membalikkan matriks $M$ bersama matriks lain yang sudah ditetapkan pada awal proses menjadi matriks identitas.
2. Mengubah matriks $M$ asli menjadi matriks identitas dengan menggunakan operasi dasar yang disebut pengurangan baris dan dilakukan secara paralel.
3. Setelah matriks $M$ asli menjadi matriks identitas, matriks kedua akan menjadi $M^{-1}$ matriks inversi.

# Penyelesaian Matriks Invers dengan Eliminasi Gauss Jordan

Persamaan matriks:

$$ 2x_1 + x_2 + 3x_3 + 2x_4 = 2 \\
x_1 + 2x_2 + 3x_3 + x_4 = 4 \\
x_1 + 3x_2 + x_3 + x_4 = 5 \\
2x_1 + x_2 + x_3 + 4x_4 = 6 \\ $$

In [1]:
import numpy as np
A = np.array([[2,1,3,2],[1,2,3,1],[1,3,1,1],[2,1,1,4]])
I = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])

print(A)
print(I)

[[2 1 3 2]
 [1 2 3 1]
 [1 3 1 1]
 [2 1 1 4]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [2]:
# Fungsi untuk menukar 2 baris
# A adalah matriks NumPy yang akan dimodifikasi
# k, l adalah indeks baris yang akan ditukar
def RowSwap(A,k,l):
    m = A.shape[0]  # m adalah nomor dari baris A
    n = A.shape[1]  # n adalah nomor dari kolom A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

# Fungsi untuk mengalikan baris yang bukan nol
# A adalah matriks NumPy yang akan dimodifikasi
def RowScale(A,k,scale):
    m = A.shape[0]  # m adalah nomor dari baris A
    n = A.shape[1]  # n adalah nomor dari kolom A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

# Fungsi untuk mengalikan sebuah konstanta ke satu baris dan menambahkan ke baris lainnya
# l adalah baris yang sudah ditambahkan ke dalam baris k
def RowAdd(A,k,l,scale):
    m = A.shape[0]  # m adalah nomor dari baris A
    n = A.shape[1]  # n adalah nomor dari kolom A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [3]:
# Mengalikan baris indeks 0 dengan 1/2
A1 = RowScale(A,0,1/2)
print(A1)
I1 = RowScale(I,0,1/2)
print(I1)

[[1.  0.5 1.5 1. ]
 [1.  2.  3.  1. ]
 [1.  3.  1.  1. ]
 [2.  1.  1.  4. ]]
[[0.5 0.  0.  0. ]
 [0.  1.  0.  0. ]
 [0.  0.  1.  0. ]
 [0.  0.  0.  1. ]]


In [4]:
# Menambahkan baris indeks 0 dengan baris indeks 1 yang sudah dikalikan -1
A2 = RowAdd(A1,0,1,-1)
print(A2)
I2 = RowAdd(I1,0,1,-1)
print(I2)

[[1.  0.5 1.5 1. ]
 [0.  1.5 1.5 0. ]
 [1.  3.  1.  1. ]
 [2.  1.  1.  4. ]]
[[ 0.5  0.   0.   0. ]
 [-0.5  1.   0.   0. ]
 [ 0.   0.   1.   0. ]
 [ 0.   0.   0.   1. ]]


In [5]:
# Menambahkan baris indeks 0 dengan baris indeks 2 yang sudah dikalikan -1
A3 = RowAdd(A2,0,2,-1)
print(A3)
I3 = RowAdd(I2,0,2,-1)
print(I3)

[[ 1.   0.5  1.5  1. ]
 [ 0.   1.5  1.5  0. ]
 [ 0.   2.5 -0.5  0. ]
 [ 2.   1.   1.   4. ]]
[[ 0.5  0.   0.   0. ]
 [-0.5  1.   0.   0. ]
 [-0.5  0.   1.   0. ]
 [ 0.   0.   0.   1. ]]


In [6]:
# Menambahkan baris indeks 0 dengan baris indeks 3 yang sudah dikalikan dengan -2
A4 = RowAdd(A3,0,3,-2)
print(A4)
I4 = RowAdd(I3,0,3,-2)
print(I4)

[[ 1.   0.5  1.5  1. ]
 [ 0.   1.5  1.5  0. ]
 [ 0.   2.5 -0.5  0. ]
 [ 0.   0.  -2.   2. ]]
[[ 0.5  0.   0.   0. ]
 [-0.5  1.   0.   0. ]
 [-0.5  0.   1.   0. ]
 [-1.   0.   0.   1. ]]


In [7]:
# Mengalikan baris indeks 1 dengan 2/3
A5 = RowScale(A4,1,2/3)
print(A5)
I5 = RowScale(I4,1,2/3)
print(I5)

[[ 1.   0.5  1.5  1. ]
 [ 0.   1.   1.   0. ]
 [ 0.   2.5 -0.5  0. ]
 [ 0.   0.  -2.   2. ]]
[[ 0.5         0.          0.          0.        ]
 [-0.33333333  0.66666667  0.          0.        ]
 [-0.5         0.          1.          0.        ]
 [-1.          0.          0.          1.        ]]


In [8]:
# Menambahkan baris indeks 1 dengan baris indeks 0 dengan -0,5
A6 = RowAdd(A5,1,0,-0.5)
print(A6)
I6 = RowAdd(I5,1,0,-0.5)
print(I6)

[[ 1.   0.   1.   1. ]
 [ 0.   1.   1.   0. ]
 [ 0.   2.5 -0.5  0. ]
 [ 0.   0.  -2.   2. ]]
[[ 0.66666667 -0.33333333  0.          0.        ]
 [-0.33333333  0.66666667  0.          0.        ]
 [-0.5         0.          1.          0.        ]
 [-1.          0.          0.          1.        ]]


In [9]:
# Menambahkan baris indeks 1 dengan baris indeks 2 yang sudah dikalikan -2,5
A7 = RowAdd(A6,1,2,-2.5)
print(A7)
I7 = RowAdd(I6,1,2,-2.5)
print(I7)

[[ 1.  0.  1.  1.]
 [ 0.  1.  1.  0.]
 [ 0.  0. -3.  0.]
 [ 0.  0. -2.  2.]]
[[ 0.66666667 -0.33333333  0.          0.        ]
 [-0.33333333  0.66666667  0.          0.        ]
 [ 0.33333333 -1.66666667  1.          0.        ]
 [-1.          0.          0.          1.        ]]


In [10]:
# Mengalikan baris indeks 2 dengan 1/-3
A8 = RowScale(A7,2,1/-3)
print(A8)
I8 = RowScale(I7,2,1/-3)
print(I8)

[[ 1.  0.  1.  1.]
 [ 0.  1.  1.  0.]
 [-0. -0.  1. -0.]
 [ 0.  0. -2.  2.]]
[[ 0.66666667 -0.33333333  0.          0.        ]
 [-0.33333333  0.66666667  0.          0.        ]
 [-0.11111111  0.55555556 -0.33333333 -0.        ]
 [-1.          0.          0.          1.        ]]


In [11]:
# Menambahkan baris indeks 2 dengan baris indeks 0 yang sudah dikalikan 1/-1
A9 = RowAdd(A8,2,0,1/-1)
print(A9)
I9 = RowAdd(I8,2,0,1/-1)
print(I9)

[[ 1.  0.  0.  1.]
 [ 0.  1.  1.  0.]
 [-0. -0.  1. -0.]
 [ 0.  0. -2.  2.]]
[[ 0.77777778 -0.88888889  0.33333333  0.        ]
 [-0.33333333  0.66666667  0.          0.        ]
 [-0.11111111  0.55555556 -0.33333333 -0.        ]
 [-1.          0.          0.          1.        ]]


In [12]:
# Menambahkan baris indeks 2 dengan baris indeks 1 yang sudah dikalikan 1/-1
A10 = RowAdd(A9,2,1,1/-1)
print(A10)
I10 = RowAdd(I9,2,1,1/-1)
print(I10)

[[ 1.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1. -0.]
 [ 0.  0. -2.  2.]]
[[ 0.77777778 -0.88888889  0.33333333  0.        ]
 [-0.22222222  0.11111111  0.33333333  0.        ]
 [-0.11111111  0.55555556 -0.33333333 -0.        ]
 [-1.          0.          0.          1.        ]]


In [13]:
# Menambahkan baris indeks 2 dengan baris indeks 3 yang sudah dikalikan 2
A11 = RowAdd(A10,2,3,2)
print(A11)
I11 = RowAdd(I10,2,3,2)
print(I11)

[[ 1.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1. -0.]
 [ 0.  0.  0.  2.]]
[[ 0.77777778 -0.88888889  0.33333333  0.        ]
 [-0.22222222  0.11111111  0.33333333  0.        ]
 [-0.11111111  0.55555556 -0.33333333 -0.        ]
 [-1.22222222  1.11111111 -0.66666667  1.        ]]


In [14]:
# Mengalikan baris indeks 3 dengan 1/2
A12 = RowScale(A11,3,1/2)
print(A12)
I12 = RowScale(I11,3,1/2)
print(I12)

[[ 1.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1. -0.]
 [ 0.  0.  0.  1.]]
[[ 0.77777778 -0.88888889  0.33333333  0.        ]
 [-0.22222222  0.11111111  0.33333333  0.        ]
 [-0.11111111  0.55555556 -0.33333333 -0.        ]
 [-0.61111111  0.55555556 -0.33333333  0.5       ]]


In [15]:
# Menambahkan baris indeks 3 dengan baris indeks 0 yang sudak dikalikan 1/-1
A13 = RowAdd(A12,3,0,1/-1)
print(A13)
I13 = RowAdd(I12,3,0,1/-1)
print(I13)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1. -0.]
 [ 0.  0.  0.  1.]]
[[ 1.38888889 -1.44444444  0.66666667 -0.5       ]
 [-0.22222222  0.11111111  0.33333333  0.        ]
 [-0.11111111  0.55555556 -0.33333333 -0.        ]
 [-0.61111111  0.55555556 -0.33333333  0.5       ]]


In [16]:
# Mencari hasil X1, X2, X3, X4
B = np.array([[1.38888889,-1.44444444,0.66666667,-0.5],[-0.22222222,0.11111111,0.33333333,0],[-0.11111111,0.55555556,-0.33333333,-0],[-0.61111111,0.55555556,-0.33333333,0.5]])
C = np.array([[2],[4],[5],[6]])
print(B@C)

[[-2.66666663]
 [ 1.66666665]
 [ 0.33333337]
 [ 2.33333337]]


In [2]:
# Fungsi untuk menukar 2 baris
# A adalah matriks NumPy yang akan dimodifikasi
# k, l adalah indeks baris yang akan ditukar
def RowSwap(A,k,l):
    m = A.shape[0]  # m adalah nomor dari baris A
    n = A.shape[1]  # n adalah nomor dari kolom A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

# Fungsi untuk mengalikan baris yang bukan nol
# A adalah matriks NumPy yang akan dimodifikasi
def RowScale(A,k,scale):
    m = A.shape[0]  # m adalah nomor dari baris A
    n = A.shape[1]  # n adalah nomor dari kolom A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

# Fungsi untuk mengalikan sebuah konstanta ke satu baris dan menambahkan ke baris lainnya
# l adalah baris yang sudah ditambahkan ke dalam baris k
def RowAdd(A,k,l,scale):
    m = A.shape[0]  # m adalah nomor dari baris A
    n = A.shape[1]  # n adalah nomor dari kolom A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

$ 2x_1 + x_2 + 2x_3 = 2 \\
4x_1 + 2x_2 + 6x_3 = 3 \\
2x_1 + 2x_2 + 4x_3 = 4 \\
$

In [60]:
import numpy as np
A1 = np.array([[2,1,2,1,0,0],[4,2,6,0,1,0],[2,2,4,0,0,1]])
print(A1)

[[2 1 2 1 0 0]
 [4 2 6 0 1 0]
 [2 2 4 0 0 1]]


In [61]:
B1 = RowScale(A1,0,0.5)
print(B1)

[[1.  0.5 1.  0.5 0.  0. ]
 [4.  2.  6.  0.  1.  0. ]
 [2.  2.  4.  0.  0.  1. ]]


In [62]:
C1 = RowAdd(B1,0,1,-4)
print(C1)

[[ 1.   0.5  1.   0.5  0.   0. ]
 [ 0.   0.   2.  -2.   1.   0. ]
 [ 2.   2.   4.   0.   0.   1. ]]


In [63]:
D1 = RowAdd(C1,0,2,-2)
print(D1)

[[ 1.   0.5  1.   0.5  0.   0. ]
 [ 0.   0.   2.  -2.   1.   0. ]
 [ 0.   1.   2.  -1.   0.   1. ]]


In [64]:
E1 = RowSwap(D1,1,2)
print(E1)

[[ 1.   0.5  1.   0.5  0.   0. ]
 [ 0.   1.   2.  -1.   0.   1. ]
 [ 0.   0.   2.  -2.   1.   0. ]]


In [65]:
F1 = RowAdd(E1,1,0,-0.5)
print(F1)

[[ 1.   0.   0.   1.   0.  -0.5]
 [ 0.   1.   2.  -1.   0.   1. ]
 [ 0.   0.   2.  -2.   1.   0. ]]


In [67]:
G1 = RowScale(F1,2,0.5)
print(G1)

[[ 1.   0.   0.   1.   0.  -0.5]
 [ 0.   1.   2.  -1.   0.   1. ]
 [ 0.   0.   1.  -1.   0.5  0. ]]


In [70]:
H1 = RowAdd(G1,2,1,-2)
print(H1)

[[ 1.   0.   0.   1.   0.  -0.5]
 [ 0.   1.   0.   1.  -1.   1. ]
 [ 0.   0.   1.  -1.   0.5  0. ]]


In [77]:
Ain = H1[:,3:6]
Ain

array([[ 1. ,  0. , -0.5],
       [ 1. , -1. ,  1. ],
       [-1. ,  0.5,  0. ]])

In [78]:
A2 = np.array([[1,0,-0.5],[1,-1,1],[-1,0.5,0]])
A = np.array([[2,1,2],[4,2,6],[2,2,4]])

print(A@Ain)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
